<?php

return [
  'corrections' => [
    'gmal.com' => 'gmail.com',
    'hotail.com' => 'hotmail.com',
    'yaho.com' => 'yahoo.com',
    'outlok.com' => 'outlook.com',
    'gmai.com' => 'gmail.com',
    'hotmai.com' => 'hotmail.com',
    'ahoo.com' => 'yahoo.com',
    'outloo.com' => 'outlook.com',
    'gmail.co' => 'gmail.com',
    'hotmail.co' => 'hotmail.com',
    'yahoo.co' => 'yahoo.com',
    'outlook.co' => 'outlook.com',
    'gmil.com' => 'gmail.com',
    'hotmil.com' => 'hotmail.com',
    'yhoo.com' => 'yahoo.com',
    'otlook.com' => 'outlook.com',
    'gmail.colm' => 'gmail.com',
    'hotmail.coml' => 'hotmail.com',
    'yahoo.coml' => 'yahoo.com',
    'outlook.coml' => 'outlook.com',
    'hotmal.com' => 'hotmail.com',
    'hotmail.com.br' => 'hotmail.com',
    'outlook.com.br' => 'outlook.com',
    'gmail' => 'gmail.com',
    'hotmail' => 'hotmail.com',
    'yahoo' => 'yahoo.com',
    'outlook' => 'outlook.com',
    'gmal' => 'gmail.com',
    'hotail' => 'hotmail.com',
    'hotmal' => 'hotmail.com',
    'hotmail.br' => 'hotmail.com',
    'outlook.br' => 'outlook.com',
    'yhoo' => 'yahoo.com',
    'otlook' => 'outlook.com',
  ],
  
  'message' => 'Did you mean @:correct_domain?'
];